version: '3.9'

services:  
  session-db:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sessiondb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55
    networks:
      - session-network
    container_name: session_db

networks: 
  session-network:
    name: session-network