
name: Build and push on Docker Hub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        # add here to test with different os
        os: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag khalld/session-db:latest
    - name: Push on Docker Hub
      run: docker push khalld/session-db:latest
